[package]
name = "crabby-auth"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = { version = "0.5.3", features = ["password-hash"] }
tokio-macros = "2.5.0"
dashmap = "6.1.0"
prost = "*"
tracing = "0.1.41"
tracing-opentelemetry = "0.31.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
tonic = "*"
uuid = { version = "1.17.0", features = [
    "fast-rng",
    "v7",
    "v4",
    "serde",
    "macro-diagnostics",
] }
sqlx = { version = "0.8.6", features = [
    "postgres",
    "migrate",
    "runtime-tokio",
    "uuid",
    "chrono",
] }
anyhow = "1.0.98"
chrono = { version = "0.4.41", features = ["serde", "now"] }
dotenvy = "0.15.7"
pasetors = { version = "0.7.6", features = ["v4", "paserk"] }
[build-dependencies]
tonic-build = "*"
[dev-dependencies]
faker_rand = "0.1.1"
rand = "0.9.1"
