workspace = { members = ["custom-images"] }
[package]
name = "crabby-auth"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-macros = "2.2.0"
dashmap = "5.5.3"
prost = "0.12.4"
rust-argon2 = "2.1.0"
rusty_paseto = "0.6.1"
tracing = "0.1.40"
tracing-opentelemetry = "0.23.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.11.0"
uuid = { version = "1.8.0", features = [
    "fast-rng",
    "v7",
    "v4",
    "serde",
    "macro-diagnostics",
] }
sqlx = { version = "0.7.4", features = [
    "postgres",
    "migrate",
    "runtime-tokio",
    "uuid",
    "chrono",
] }
anyhow = "1.0.86"
chrono = { version = "0.4.38", features = ["serde"] }
[build-dependencies]
tonic-build = "0.11"
[dev-dependencies]
faker_rand = "0.1.1"
rand = "0.8.5"
