[env]
SUPER_SECRET_KEY = "baxy_made_this"
PGHOST = "localhost"
PGUSER = "crabby"
PGPASSWORD = "test"
PGDATABASE = "crabby_userdb"
DATABASE_URL = "postgresql://auth_login@127.0.0.1:26257/crabby_authdb?sslmode=disable"
PGSSLROOTCERT = "../../docker/volumes/certs/ca.crt"
PGSSLCERT = "../../docker/volumes/certs/client.crabby.crt"
PGSSLKEY = "../../docker/volumes/certs/client.crabby.key"
PGSSLMODE = "VerifyFull"
PGPORT = 26257
